
server:
  port: 9000

security:
  user:
    name: configserver
#   To use cipher, intall JCE:
#   http://suhothayan.blogspot.ru/2012/05/how-to-install-java-cryptography.html
#
#   The password is encrypted by this:
#   http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_encryption_and_decryption
#   the password is 'configserver_password'
    password: configserver_password

eureka:
  instance:
    metadataMap:
      user:     ${security.user.name}
      password: ${security.user.password}
