
server:
  port: 9090

security.basic.enabled: false

---
spring:
  profiles: zone1

eureka:
  instance:
    metadataMap:
      container:
        color: green

---
spring:
  profiles: zone2

eureka:
  instance:
    metadataMap:
      container:
        color: blue
