
server:
  port: 9091

security.basic.enabled: false

---
spring:
  profiles: zone1

eureka:
  instance:
    metadataMap:
      container:
        color: green

---
spring:
  profiles: zone2


server:
  port: 9092

eureka:
  instance:
    status: OUT_OF_SERVICE
    metadataMap:
      container:
        color: blue
